// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Prisma 7: connection URL живёт здесь, не в schema.prisma.
// CLI (migrate/studio/db seed) ходит ПРЯМЫМ коннектом Neon — env("DIRECT_URL"):
// pooled PgBouncer ломает DDL и advisory-lock миграций.
// Рантайм приложения остаётся на pooled DATABASE_URL — см. lib/prisma.ts.
// Внимание: env() бросает при загрузке конфига, а конфиг грузит ЛЮБАЯ команда CLI
// (включая prisma generate) → DIRECT_URL нужен во всех окружениях, в т.ч. на Vercel.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
