// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Prisma 7: connection URL живёт здесь, не в schema.prisma.
// Используем pooled DATABASE_URL — Neon-pooler тянет и DDL миграций, и рантайм.
// DIRECT_URL не задействован: direct-эндпоинт недоступен из текущей сети (WSL),
// pooler справляется. Если появится прямой коннект — можно вернуть env("DIRECT_URL").
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
